services:
  workerbee:
    container_name: workerbee
    image: workerbee
    build: ./
    restart: always
    ports:
      - "8500:8080"
    depends_on:
      workerbee_database: 
        condition: service_healthy
    env_file:
      - .env
    mem_limit: 1g
    cpus: "2.0"
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 10.177.195.1
      - 213.186.33.99

  workerbee_database:
    image: postgres:18
    container_name: workerbee_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ${INIT_SQL_FILE:-./db/init.up.sql}:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}"]
      interval: 10s
      timeout: 10s
    mem_limit: 1g
    cpus: "2.0"
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 10.177.195.1
      - 213.186.33.99

volumes:
  postgres_data:
