services:
  workerbee:
    container_name: "workerbee"
    build: ./
    depends_on:
      postgres: 
        condition: service_healthy
    env_file:
      - .env
  
  postgres:
    image: postgres:17
    container_name: workerbee-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${INIT_SQL_FILE:-./db/init.up.sql}:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
  varnish:
    image: varnish:7
    container_name: workerbee-varnish
    ports:
      - "80:80"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
    command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-s", "malloc,512m"]
    depends_on:
      - workerbee
volumes:
  postgres_data:
