services:
  workerbee:
    container_name: workerbee
    image: workerbee
    build: ./
    restart: always
    ports:
      - "8500:8080"
    depends_on:
      postgres: 
        condition: service_healthy
    env_file:
      - .env

  postgres:
    image: postgres:17
    container_name: workerbee_database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${INIT_SQL_FILE:-./db/init.up.sql}:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s

volumes:
  postgres_data:
